# Generated by Django 2.0.7 on 2018-08-18 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
